steps:
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['init']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['refresh']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
tags: ['cloud-builders-community']